config/routes.rb
Rails.application.routes.draw do

  get 'messages/create'

  get 'conversations/index'

  get 'conversations/show'

  get 'conversations/new'

  get 'conversations/create'

  resources :reviews
  resources :products
  resources :users
  resources :clinical_users
  resources :vendor_users
    resources :conversations do
	resources :messages
	end

  root 'userpaths#index'
  get 'vendor_users/new'

  get '/compare' => 'compare#index'
  get '/compare/clear' => 'compare#clearCompare'
  get '/compare/:id' => 'compare#add'

  get 'products/:id' => 'products#index'

  get 'clinical_users/new'

  get 'sessions/new'

  get 'userpaths/index'

  get 'userpaths/index'

  get 'users/new'

  get 'home/index'
  
  get 'home/about'
  
  get '/about' => 'home#about'
  
  get 'home/privacy'
  
  get '/privacy' => 'home#privacy'
  
  get 'home/new'

  get 'welcome/productpage'

  get 'ProductList' => 'product_list#index'
  post 'ProductList' => 'product_list#index'
  get 'pages/home'

  get 'Favorites' => 'favorites#index'
  post 'Favorites' => 'favorites#index'
 

  get 'signup'  => 'users#new'
  get 'signupVendor'  => 'vendor_users#new'
  get 'signupClinic'  => 'clinical_users#new'
  

  get    'login'   => 'sessions#newVendor'
  post   'login'   => 'sessions#createvendor'

  get    'loginVendor'   => 'sessions#newVendor'
  post   'loginVendor'   => 'sessions#createVendor'

  
  get    'loginHGO'   => 'sessions#newHGO'
  post   'loginHGO'   => 'sessions#createHGO'

  delete 'logout'  => 'sessions#destroy'

  

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :reviews
	belongs_to :vendor_user
	belongs_to :vendor_organization

	# This is from the carrierwave gem and
	# alllows vendors to upload images for their
	# products.
	mount_uploader :image, ImageUploader
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    @reviews = Review.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
   @product = Product.new(product_params)
   @product.vendor_user_id = current_user.id
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
      @reviews = Review.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :SKU, :description, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">

<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form">
      <div class="form-group">
        <div class="col-xs-6">
          <div class="col-xs-6">
          </div>
          <div class="col-xs-6">
            <%= f.label :Name %><br>
            <%= f.text_field :name, placeholder: "Enter a Name", class: 'form-control' %>    <br>        
            <%= f.label :SKU, "SKU" %><br>
            <%= f.number_field :SKU, placeholder: "Enter a SKU", class: 'form-control'%><br>

            <%= f.label :name, "Upload an Image"%><br>
            <%= f.file_field :image %><br>

            <%= f.label :Price %><br>
            <%= f.number_field :price, :step => 'any', placeholder: "Enter a Price", class: 'form-control' %><br>

            <h4> <strong> Research Links </strong> </h4>
            <%= f.label :name, "Clinical Research"%><br>
            <%= f.text_field :research, placeholder: "Enter a Research Link", class: 'form-control' %>    <br>   
            <%= f.label :name, "Clinical Research"%><br>
            <%= f.text_field :research2, placeholder: "Enter a Research Link", class: 'form-control' %>    <br>   
            <%= f.label :name, "Clinical Research" %><br>
            <%= f.text_field :research3, placeholder: "Enter a Research Link", class: 'form-control' %>    <br>   

            <br><br>


             <%= f.submit "Create a Product", class: "btn btn-primary" %>

            </div>

            
           
      
       </div>
      </div>
    </div>

    <div class="form">
      <div class="form-group">
        <div class="col-xs-6">
           <div class="col-xs-6">
           <h4><strong> Product Information </strong></h4>
          <%= f.label :Description %><br>
          <%= f.text_area :description, placeholder: "Enter a Description", class: 'form-control' %><br>

          <%= f.label :Features %><br>
          <%= f.text_area :features, placeholder: "Enter Product Features", class: 'form-control' %><br>

          <%= f.label :Height %><br>
          <%= f.text_field :height, placeholder: "Enter Height", class: 'form-control' %><br>

          <%= f.label :Width %><br>
          <%= f.text_field :width, placeholder: "Enter Width", class: 'form-control' %><br>

          <%= f.label :Depth %><br>
          <%= f.text_field :depth, placeholder: "Enter Depth", class: 'form-control' %>
         
          </div>
       </div>
      </div>
    </div>

  <div class="field">
   

  </div>
<% end %>

</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="container">
<div class="row">
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>
</div>
</div>

app/views/products/new.html.erb
<h1>Create a New Product</h1>

<%= render 'form' %>

<% link_to 'Back', products_path %>

app/views/products/show.html.erb
<div id = "prod_page">

<div id = "prod_img">
	<!--Images are housed in public/uploads/product/image and will correspond to each product so we don't need to have an absolute path just @product.image -->
	<img src="<%= @product.image %>" alt="http://placehold.it/320x150" style="width:auto;height:400px;">
</div>

<div id = "prod_header">
	<h2><%= @product.name %></h2><br>
		<%if isvendor %>
			<!-- vendors don't see favorites -->
		<%else%>
			<button type="submit" class="btn btn-default filter-col" name="add" id="add">Add to Favorites</button>
		<%end%>
		&nbsp;&nbsp;&nbsp;&nbsp;
		<a href="/compare/<%= @product.id %>" type="submit" class="btn btn-default filter-col" onmouseover = "this.style.color='black'">Add to Compare</a>
	<hr class = "hr_style">
	 
	<table id = "prod_info">
		<tr>
            <td> <span> SKU: </span> </td>
            <td><%= @product.SKU %></td>
        </tr>
        <tr>
            <td> <span> Price: </span> </td>
            <td> <%= @product.price %> </td>
        </tr>
		<% if !@product.warranty.blank? %>
			<tr>
				<td> <span> Warranty: </span> </td>
				<td> <%= @product.warranty %> </td> 
			</tr>
		<%end%>
        <% if !@product.height.blank? || !@product.height.blank? || !@product.width.blank? %>
            <tr>
                <td><span>Product Dimensions</span></td>
            </tr>
        <%end%>
        
		<% if !@product.height.blank? %>
            <tr>
                <td>&nbsp;&nbsp;Height: </td>
                <td><%= @product.height %>"</td>
            </tr>
        <%end%>
                
        <% if !@product.depth.blank? %>
            <tr>
                <td>&nbsp;&nbsp;Depth: </td>
                <td><%= @product.depth %>"</td>
            </tr>
        <%end%>
                
        <% if !@product.width.blank? %>
            <tr>
                <td>&nbsp;&nbsp;Width: </td>
                <td><%= @product.width %>"</td>
            </tr>
        <%end%>
    </table>
	
	<hr class = "hr_style">
</div>
</div>

<div id = "prod_descript">
	<br>
        <h3> Product Description </h3><br>
            <p><%= @product.description %></p>
        <br> 
        <h3> Product Features </h3>
            <p><%= @product.features %> Product features go here.</p> 
		<br>
	<hr class = "hr_style">
</div>

<div id = "prod_research">
    <h3>Clinical Research </h3>
		<ul>
			<% if !@product.research.blank? %>
			<li><a href="<%= @product.research %>">Click here for further research!</a></li>
			<% end %>
			<% if !@product.research2.blank? %>
			<li><a href="<%= @product.research2 %>">Click here for further research!</a></li>
			<% end %>
			<% if !@product.research3.blank? %>
			<li><a href="<%= @product.research3 %>">Click here for further research!</a></li>
			<% end %>
		</ul>
		<br><hr class = "hr_style">
</div>

<div id = "review">  
	<%= form_for(@review) do |f| %>
        <% if @review.errors.any? %>
            <div id="error_explanation">
                <h3><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h3>

                <ul>
                    <% @review.errors.full_messages.each do |message| %>
					<li><%= message %></li>
                    <% end %>
                </ul>
			</div>
		<% end %>
			
		<br></br>
		<div class="field">
			<h3><%= f.label :Leave_a_Review!, "Leave a Review!" %></h3>
			<%= f.text_area :content, class: 'form-control' %>
			<br>
		</div>
    
		<div class="field">
			<%= f.label :rating %><br>
			<%= f.number_field :rating, in: 1..5, class: 'form-control' %>
			<br>
		</div>

		<div class="field">
			<%= f.label :product_id %><br>
			<%= f.number_field :product_id, class: 'form-control' %>
			<br>
		</div>
    
		<div class="actions">
			<%= f.submit "Create Review", class: "btn btn-primary" %>
		</div>
    <% end %>
	
</div>
	
<div id = "review_results">	
	<br><hr class = "hr_style"><br>
		<h3>Product Reviews</h3><br>
		<% if @reviews.product.length > 0 %>
			<table class = "review_table">
				<tr>
					<th>Review</th>
					<th>Rating</th>
				</tr>
			<% @reviews.each do |review| %>
				<% if review.product_id == @product.id %>
					
					<tr>
						<td> <%= review.content %></td>
						<td> <%= review.rating %></td>
					</tr>        	
				<%end%>
			<%end%> 
		<% else %>
			<p>There are no reviews at this time.</p>
		<%end%>
    
  
    </table>
	<br>
	<br>
</div>